#ifndef ERROR_TYPE_H
#define ERROR_TYPE_H

enum class ErrorType : char
{
	ET_SUCCESS = 0,
	ET_WINDOW_CREATION_FAILED,
	ET_GLAD_INITIALISATION_FAILED,
	ET_VERTEX_SHADER_COMPILATION_FAILED,
	ET_FRAGMENT_SHADER_COMPILATION_FAILED,
	ET_SHADER_PROGRAM_LINK_FAILED,
	ET_COUNT

};

#endif // !ERROR_TYPE_H

