#ifndef ERROR_TYPE_H
#define ERROR_TYPE_H

enum class E_ERROR_TYPE : char
{
	ET_SUCCESS = 0,
	ET_WINDOW_CREATION_FAILED,
	ET_GLAD_INITIALISATION_FAILED,
	ET_VERTEX_SHADER_COMPILATION_FAILED,
	ET_FRAGMENT_SHADER_COMPILATION_FAILED,
	ET_SHADER_PROGRAM_LINK_FAILED,
	ET_FILE_READ_FAILED,
	ET_STREAM_STILL_OPEN,
	ET_DATA_MANAGER_INIT_FAILED,
	ET_FAILED_LOAD_TEXTURE,
	ET_ASSIMP_MESH_FAILED_READING_FILE,
	ET_COUNT

};

#endif // !ERROR_TYPE_H

